# Generated by Django 5.1 on 2024-09-04 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_runner", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="testcase",
            name="stream",
            field=models.CharField(
                blank=True,
                choices=[("core", "aiml"), ("Core", "AI-ML")],
                max_length=20,
                null=True,
            ),
        ),
    ]
