# Generated by Django 5.1 on 2024-09-04 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_runner", "0002_testcase_stream"),
    ]

    operations = [
        migrations.RenameField(
            model_name="testrun",
            old_name="error",
            new_name="error_stack",
        ),
        migrations.AddField(
            model_name="testrun",
            name="error_code",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="testcase",
            name="controllers",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name="testcase",
            name="stream",
            field=models.CharField(
                blank=True,
                choices=[("core", "Core"), ("aiml", "AI-ML")],
                max_length=20,
                null=True,
            ),
        ),
    ]
