# Generated by Django 5.1 on 2024-08-27 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_runner", "0002_testcaseresult_zipped_log"),
    ]

    operations = [
        migrations.AddField(
            model_name="testrun",
            name="nickname",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
