# Generated by Django 5.1 on 2024-08-27 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_runner", "0003_testrun_nickname"),
    ]

    operations = [
        migrations.AddField(
            model_name="testrun",
            name="category",
            field=models.CharField(
                choices=[
                    ("stress", "Stress"),
                    ("functional", "Functional"),
                    ("hammer", "Hammer"),
                    ("sanity", "Sanity"),
                ],
                default="functional",
                max_length=20,
            ),
        ),
    ]
