# Generated by Django 5.1 on 2024-09-05 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "test_runner",
            "0003_rename_error_testrun_error_stack_testrun_error_code_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="ctrlpackagerepo",
            name="local_path",
            field=models.TextField(blank=True, null=True),
        ),
    ]
