# Generated by Django 5.1 on 2024-09-06 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_runner", "0004_ctrlpackagerepo_local_path"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testrun",
            name="test_job",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="test_job",
                to="test_runner.testjob",
            ),
        ),
    ]
