# Generated by Django 5.1 on 2024-08-29 01:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_runner", "0006_virtualenvironment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Server",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("ip", models.GenericIPAddressField()),
                ("capacity", models.IntegerField()),
                ("current_load", models.IntegerField()),
                ("port", models.IntegerField()),
                ("username", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "os_name",
                    models.CharField(
                        choices=[("rhel", "RHEL"), ("windows", "Windows")],
                        max_length=100,
                    ),
                ),
                ("kernel", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="virtualenvironment",
            name="assigned_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="virtualenvironment",
            name="ctrl_package_version",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="virtualenvironment",
            name="last_used_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="virtualenvironment",
            name="lease_duration",
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="virtualenvironment",
            name="requirements",
            field=models.FileField(blank=True, null=True, upload_to="requirements/"),
        ),
        migrations.AddField(
            model_name="virtualenvironment",
            name="script",
            field=models.FileField(blank=True, null=True, upload_to="scripts/"),
        ),
        migrations.AlterField(
            model_name="virtualenvironment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="venv",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="virtualenvironment",
            name="server",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="venv",
                to="test_runner.server",
            ),
        ),
    ]
