# Generated by Django 5.1.1 on 2024-09-12 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("test_runner", "0006_requirementsmodel_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="virtualenvironment",
            name="unique_venv_name_per_user",
        ),
    ]
