# Generated by Django 5.1 on 2024-08-29 14:56

import test_runner.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_runner", "0007_server_virtualenvironment_assigned_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="virtualenvironment",
            name="requirements",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=test_runner.models.requirements_upload_path,
            ),
        ),
    ]
