# Generated by Django 5.1.1 on 2024-09-13 01:44

import django.db.models.deletion
from django.db import migrations, models

import test_runner.models


def fix_requirements_field(apps, schema_editor):
    VirtualEnvironment = apps.get_model("test_runner", "VirtualEnvironment")
    db_alias = schema_editor.connection.alias
    VirtualEnvironment.objects.using(db_alias).filter(requirements="").update(
        requirements=None
    )


class Migration(migrations.Migration):
    dependencies = [
        ("test_runner", "0007_remove_virtualenvironment_unique_venv_name_per_user"),
    ]

    operations = [
        migrations.RunPython(fix_requirements_field),  # Custom step to fix data
        migrations.RemoveField(
            model_name="virtualenvironment",
            name="requirement_file",
        ),
        migrations.AddField(
            model_name="virtualenvironment",
            name="requirements_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=test_runner.models.requirements_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="virtualenvironment",
            name="requirements",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="test_runner.requirementsmodel",
            ),
        ),
    ]
