# Generated by Django 5.1.1 on 2024-09-13 01:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_runner", "0008_remove_virtualenvironment_requirement_file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="virtualenvironment",
            name="requirements",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="test_runner.requirementsmodel",
            ),
        ),
    ]
