# Generated by Django 5.1.1 on 2024-09-13 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("test_runner", "0009_alter_virtualenvironment_requirements"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="virtualenvironment",
            name="requirements",
        ),
    ]
