# Generated by Django 5.1.1 on 2024-09-13 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_runner", "0010_remove_virtualenvironment_requirements"),
    ]

    operations = [
        migrations.RenameField(
            model_name="virtualenvironment",
            old_name="requirements_file",
            new_name="requirements",
        ),
        migrations.AddField(
            model_name="virtualenvironment",
            name="requirements_text",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="test_runner.requirementsmodel",
            ),
        ),
    ]
