# Generated by Django 5.1 on 2024-08-29 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_runner", "0012_testjob"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="testjob",
            name="user",
        ),
        migrations.RemoveField(
            model_name="testjob",
            name="venv",
        ),
        migrations.AddField(
            model_name="virtualenvironment",
            name="test_jobs",
            field=models.ManyToManyField(related_name="venv", to="test_runner.testjob"),
        ),
    ]
