# Generated by Django 5.1 on 2024-08-30 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_runner", "0015_rename_log_file_path_testjob_celery_result_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testjob",
            name="retry_delay",
            field=models.IntegerField(default=60),
        ),
    ]
