# Generated by Django 5.1 on 2024-08-30 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("test_runner", "0017_testrun_error_alter_testrun_log_alter_testrun_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="testrun",
            old_name="log",
            new_name="log_file",
        ),
    ]
