# Generated by Django 5.1 on 2024-08-30 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_runner", "0021_alter_virtualenvironment_test_jobs"),
    ]

    operations = [
        migrations.CreateModel(
            name="CtrlPackageRepo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("folder_names", models.JSONField(default=list)),
                ("last_scanned", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
