# Generated by Django 5.1 on 2024-08-30 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("test_runner", "0022_ctrlpackagerepo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ctrlpackagerepo",
            old_name="folder_names",
            new_name="repo_versions",
        ),
    ]
