# Generated by Django 5.1 on 2024-08-30 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_runner", "0023_rename_folder_names_ctrlpackagerepo_repo_versions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testcase",
            name="title",
            field=models.CharField(max_length=250),
        ),
        migrations.CreateModel(
            name="SubTests",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("path", models.CharField(max_length=500)),
                (
                    "test_case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subtests",
                        to="test_runner.testcase",
                    ),
                ),
            ],
        ),
    ]
