# Generated by Django 5.1 on 2024-08-31 10:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sutclient", "0009_alter_rmii_instance_id"),
        ("test_runner", "0025_rename_name_virtualenvironment_venv_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="virtualenvironment",
            name="unique_venv_name_per_user",
        ),
        migrations.AddConstraint(
            model_name="virtualenvironment",
            constraint=models.UniqueConstraint(
                fields=("user", "venv_name"), name="unique_venv_name_per_user"
            ),
        ),
    ]
