# Generated by Django 5.1 on 2024-08-31 14:59

import test_runner.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_runner", "0027_testrun_report_file_alter_testrun_log_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testrun",
            name="log_file",
            field=models.FileField(
                blank=True,
                max_length=500,
                null=True,
                upload_to=test_runner.models.create_path,
            ),
        ),
        migrations.AlterField(
            model_name="testrun",
            name="report_file",
            field=models.FileField(
                blank=True,
                max_length=500,
                null=True,
                upload_to=test_runner.models.create_path,
            ),
        ),
    ]
