# Generated by Django 5.1 on 2024-08-31 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_runner", "0028_alter_testrun_log_file_alter_testrun_report_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="virtualenvironment",
            name="test_jobs",
        ),
        migrations.AddField(
            model_name="testjob",
            name="venv",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="test_jobs",
                to="test_runner.virtualenvironment",
            ),
        ),
    ]
