# Generated by Django 5.1 on 2024-08-26 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TestCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tcid", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=100)),
                ("path", models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="TestCaseResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("passed", "Passed"),
                            ("failed", "Failed"),
                            ("aborted", "Aborted"),
                        ],
                        max_length=20,
                    ),
                ),
                ("output", models.TextField()),
                ("error", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("log", models.TextField(blank=True)),
                (
                    "test_case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="test_runner.testcase",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TestRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("aborted", "Aborted"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "test_cases",
                    models.ManyToManyField(
                        through="test_runner.TestCaseResult", to="test_runner.testcase"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="testcaseresult",
            name="test_run",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="test_runner.testrun"
            ),
        ),
    ]
