# Generated by Django 5.1 on 2024-08-29 15:02

import test_runner.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_runner", "0008_alter_virtualenvironment_requirements"),
    ]

    operations = [
        migrations.AlterField(
            model_name="virtualenvironment",
            name="script",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=test_runner.models.requirements_upload_path,
            ),
        ),
    ]
