# Generated by Django 5.1 on 2024-08-29 15:19

import test_runner.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_runner", "0009_alter_virtualenvironment_script"),
    ]

    operations = [
        migrations.AlterField(
            model_name="virtualenvironment",
            name="path",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="virtualenvironment",
            name="script",
            field=models.FileField(
                blank=True, null=True, upload_to=test_runner.models.scripts_upload_path
            ),
        ),
    ]
