# Generated by Django 5.1 on 2024-08-29 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sutclient", "0009_alter_rmii_instance_id"),
        ("test_runner", "0013_remove_testjob_user_remove_testjob_venv_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="virtualenvironment",
            name="config_file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sutclient.config",
            ),
        ),
    ]
