# Generated by Django 5.1 on 2024-08-30 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_runner", "0016_alter_testjob_retry_delay"),
    ]

    operations = [
        migrations.AddField(
            model_name="testrun",
            name="error",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="testrun",
            name="log",
            field=models.FileField(blank=True, null=True, upload_to="logs/"),
        ),
        migrations.AlterField(
            model_name="testrun",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("running", "Running"),
                    ("passed", "Passed"),
                    ("failed", "Failed"),
                    ("aborted", "Aborted"),
                ],
                max_length=20,
            ),
        ),
    ]
