# Generated by Django 5.1 on 2024-08-30 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_runner", "0019_alter_testrun_log_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testcase",
            name="tcid",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="testrun",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("running", "Running"),
                    ("passed", "Passed"),
                    ("failed", "Failed"),
                    ("aborted", "Aborted"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="virtualenvironment",
            name="test_jobs",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="venv", to="test_runner.testjob"
            ),
        ),
    ]
