# Generated by Django 5.1 on 2024-08-30 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_runner", "0020_alter_testcase_tcid_alter_testrun_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="virtualenvironment",
            name="test_jobs",
            field=models.ManyToManyField(
                blank=True, related_name="venv", to="test_runner.testjob"
            ),
        ),
    ]
