# Generated by Django 5.1 on 2024-08-31 14:03

import test_runner.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "test_runner",
            "0026_remove_virtualenvironment_unique_venv_name_per_user_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="testrun",
            name="report_file",
            field=models.FileField(
                blank=True, null=True, upload_to=test_runner.models.create_path
            ),
        ),
        migrations.AlterField(
            model_name="testrun",
            name="log_file",
            field=models.FileField(
                blank=True, null=True, upload_to=test_runner.models.create_path
            ),
        ),
    ]
