# Generated by Django 5.1 on 2024-09-01 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_runner", "0029_remove_virtualenvironment_test_jobs_testjob_venv"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="virtualenvironment",
            name="ctrl_package_version",
        ),
        migrations.AddField(
            model_name="virtualenvironment",
            name="ctrl_package_repo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="test_runner.ctrlpackagerepo",
            ),
        ),
    ]
