# Generated by Django 5.1 on 2024-09-01 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_runner", "0030_remove_virtualenvironment_ctrl_package_version_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ctrlpackagerepo",
            name="repo_versions",
        ),
        migrations.AddField(
            model_name="ctrlpackagerepo",
            name="repo_version",
            field=models.CharField(
                default="Controller-2.2.9a63", max_length=100, unique=True
            ),
        ),
        migrations.AddField(
            model_name="ctrlpackagerepo",
            name="url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
