# Generated by Django 5.1 on 2024-09-01 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_runner", "0031_remove_ctrlpackagerepo_repo_versions_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ctrlpackagerepo",
            name="repo_version",
            field=models.CharField(
                default="Controller-2.2.9a63", max_length=100, unique=True
            ),
        ),
    ]
