# Generated by Django 5.1 on 2024-09-01 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("test_runner", "0032_alter_ctrlpackagerepo_repo_version"),
    ]

    operations = [
        migrations.RenameField(
            model_name="virtualenvironment",
            old_name="ctrl_package_repo",
            new_name="ctrl_package_version",
        ),
    ]
