# Generated by Django 5.1 on 2024-09-01 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "test_runner",
            "0033_rename_ctrl_package_repo_virtualenvironment_ctrl_package_version",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="virtualenvironment",
            name="ctrl_package_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="venv",
                to="test_runner.ctrlpackagerepo",
            ),
        ),
    ]
