# Generated by Django 5.1 on 2024-09-04 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_runner", "0034_alter_virtualenvironment_ctrl_package_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="testcase",
            name="applicable_os",
            field=models.CharField(
                blank=True, default="linux", max_length=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="testcase",
            name="feature",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="testcase",
            name="sub_feature",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="testcase",
            name="suite_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
