# Generated by Django 5.1 on 2024-09-04 02:34

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_runner", "0036_testcase_controllers"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="testcase",
            index=models.Index(
                fields=["controllers"], name="test_runner_control_9c1b5c_idx"
            ),
        ),
        # Add date_created and date_modified fields to TestCase
        migrations.AddField(
            model_name="testcase",
            name="date_created",
            field=models.DateTimeField(
                auto_now_add=True, default=datetime.datetime.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="testcase",
            name="date_modified",
            field=models.DateTimeField(auto_now=True),
        ),
        # Add date_created and date_modified fields to SubTests
        migrations.AddField(
            model_name="subtests",
            name="date_created",
            field=models.DateTimeField(
                auto_now_add=True, default=datetime.datetime.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="subtests",
            name="date_modified",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
