# Generated by Django 5.1 on 2024-09-04 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("test_runner", "0037_testcase_test_runner_control_9c1b5c_idx"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TestCase",
        ),
        migrations.DeleteModel(
            name="SubTests",
        ),
    ]
