# Generated by Django 5.1 on 2024-09-04 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("test_runner", "0038_auto_20240904_0844"),
        ("test_runner", "0039_auto_20240904_0846"),
    ]

    operations = []
