# Generated by Django 4.2.1 on 2024-08-09 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CTRLModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ctrl_path",
                    models.CharField(
                        default="\\Lib\\Python\\Python38\\Lib\\site-packages\\controller\\",
                        max_length=550,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmailOptionsModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_email", models.EmailField(max_length=254)),
                ("recipient_list", models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name="PythonPathModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stat_py_path", models.CharField(max_length=550)),
            ],
        ),
        migrations.CreateModel(
            name="SITVersionModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stream", models.CharField(max_length=100)),
                ("old_version", models.CharField(max_length=100)),
                ("current_version", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="STATModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stat_cli_path", models.CharField(max_length=550)),
                ("xml_file_paths", models.CharField(max_length=550)),
            ],
        ),
        migrations.CreateModel(
            name="SUTClientConfigModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("config_file_path", models.CharField(max_length=500)),
                ("config_path", models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="TestConfigModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("test_config_file_path", models.CharField(max_length=550)),
                ("test_config_path", models.CharField(max_length=550)),
            ],
        ),
        migrations.CreateModel(
            name="TestSuiteModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("test_suite_file_path", models.CharField(max_length=550)),
                ("test_suite_file_name", models.CharField(max_length=550)),
            ],
        ),
        migrations.CreateModel(
            name="WaitConfigModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.IntegerField()),
                ("days", models.IntegerField()),
                ("wait_on_failure", models.BooleanField()),
                ("continue_on_test_suite_failure", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="SITModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sit_versions",
                    models.ManyToManyField(to="configfile.sitversionmodel"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ConfigurationModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ctrl_pkg",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="configfile.ctrlmodel",
                    ),
                ),
                (
                    "email_options",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="configfile.emailoptionsmodel",
                    ),
                ),
                (
                    "python_path",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="configfile.pythonpathmodel",
                    ),
                ),
                (
                    "sit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="configfile.sitmodel",
                    ),
                ),
                (
                    "stat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="configfile.statmodel",
                    ),
                ),
                (
                    "sut_client_config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="configfile.sutclientconfigmodel",
                    ),
                ),
                (
                    "test_config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="configfile.testconfigmodel",
                    ),
                ),
                (
                    "test_suites",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="configfile.testsuitemodel",
                    ),
                ),
                (
                    "wait_config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="configfile.waitconfigmodel",
                    ),
                ),
            ],
        ),
    ]
