# Generated by Django 4.2.1 on 2024-08-08 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("configfile", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="testsuitemodel",
            name="test_suite_file_name",
        ),
        migrations.RemoveField(
            model_name="testsuitemodel",
            name="test_suite_file_path",
        ),
        migrations.AddField(
            model_name="testsuitemodel",
            name="name",
            field=models.CharField(default="test", max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="TestSuiteFilePath",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("test_suite_file_path", models.CharField(max_length=550)),
                (
                    "test_suite",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_suite_file_path",
                        to="configfile.testsuitemodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TestSuiteFileName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("test_suite_file_name", models.CharField(max_length=550)),
                (
                    "test_suite",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_suite_file_name",
                        to="configfile.testsuitemodel",
                    ),
                ),
            ],
        ),
    ]
