# Generated by Django 4.2.1 on 2024-08-08 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configfile", "0002_remove_testsuitemodel_test_suite_file_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="testsuitefilepath",
            name="test_suite",
        ),
        migrations.RemoveField(
            model_name="testsuitemodel",
            name="name",
        ),
        migrations.AddField(
            model_name="testsuitemodel",
            name="test_suite_file_name",
            field=models.CharField(default="test", max_length=550),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="testsuitemodel",
            name="test_suite_file_path",
            field=models.CharField(default="test", max_length=550),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="TestSuiteFileName",
        ),
        migrations.DeleteModel(
            name="TestSuiteFilePath",
        ),
    ]
