# Generated by Django 4.2.1 on 2024-08-10 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("configfile", "0002_configurationmodel_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestSuiteFileName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("test_suite_file_name", models.CharField(max_length=550)),
            ],
        ),
        migrations.CreateModel(
            name="TestSuiteFilePath",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("test_suite_file_path", models.CharField(max_length=550)),
            ],
        ),
        migrations.CreateModel(
            name="TestSuitesPathModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "test_suite_file_name",
                    models.ManyToManyField(to="configfile.testsuitefilename"),
                ),
                (
                    "test_suite_file_path",
                    models.ManyToManyField(to="configfile.testsuitefilepath"),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="configurationmodel",
            name="test_suites",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="configfile.testsuitespathmodel",
            ),
        ),
        migrations.DeleteModel(
            name="TestSuiteModel",
        ),
    ]
