# Generated by Django 4.2.1 on 2024-08-10 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("configfile", "0003_testsuitefilename_testsuitefilepath_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecipientModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("group_name", models.CharField(max_length=100)),
                ("recipient_list", models.EmailField(max_length=254)),
            ],
        ),
        migrations.RemoveField(
            model_name="emailoptionsmodel",
            name="recipient_list",
        ),
        migrations.AddField(
            model_name="configurationmodel",
            name="recipient_list",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="configfile.recipientmodel",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="emailoptionsmodel",
            name="recipient_list",
            field=models.ManyToManyField(to="configfile.recipientmodel"),
        ),
    ]
