# Generated by Django 4.2.1 on 2024-08-10 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("configfile", "0004_recipientmodel_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipientmodel",
            name="group_name",
        ),
    ]
