# Generated by Django 4.2.1 on 2024-08-10 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("configfile", "0005_remove_recipientmodel_group_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="configurationmodel",
            name="recipient_list",
        ),
    ]
