# Generated by Django 4.2.1 on 2024-08-10 17:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configfile", "0006_remove_configurationmodel_recipient_list"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="emailoptionsmodel",
            name="recipient_list",
        ),
        migrations.DeleteModel(
            name="RecipientModel",
        ),
        migrations.AddField(
            model_name="emailoptionsmodel",
            name="recipient_list",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.EmailField(max_length=254), default=list, size=None
            ),
        ),
    ]
