# Generated by Django 4.2.1 on 2024-08-10 17:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configfile", "0007_remove_emailoptionsmodel_recipient_list_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="testsuitespathmodel",
            name="test_suite_file_name",
        ),
        migrations.RemoveField(
            model_name="testsuitespathmodel",
            name="test_suite_file_path",
        ),
        migrations.AddField(
            model_name="testsuitespathmodel",
            name="test_suite_file_name",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=550), default=list, size=None
            ),
        ),
        migrations.AddField(
            model_name="testsuitespathmodel",
            name="test_suite_file_path",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=550), default=list, size=None
            ),
        ),
    ]
