# Generated by Django 5.1.1 on 2024-10-05 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configfile", "0010_alter_yamlformatconfigfilemodel_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="yamlformatconfigfilemodel",
            name="version",
            field=models.CharField(max_length=100),
        ),
    ]
