# Generated by Django 5.1 on 2024-08-12 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sutclient", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="switches",
            name="switch_password",
            field=models.CharField(default="admin", max_length=100),
        ),
        migrations.AlterField(
            model_name="switches",
            name="switch_username",
            field=models.CharField(default="admin", max_length=100),
        ),
    ]
