# Generated by Django 5.1 on 2024-08-12 02:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sutclient", "0002_alter_switches_switch_password_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="splpkgfilepath",
            name="spl_pkg_file_path",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100),
                default=[
                    "Board_Pkg_files/NVRAM_Config/binary/BCM957508-P2100T.PKG",
                    "Board_Pkg_files/NVRAM_Config/binary/BCM957508-P2100T.PKG",
                    "Board_Pkg_files/NVRAM_Config/binary/BCM957508-P2100T.PKG",
                ],
                size=None,
            ),
        ),
    ]
