# Generated by Django 5.1 on 2024-08-12 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sutclient", "0003_alter_splpkgfilepath_spl_pkg_file_path"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="name",
            field=models.CharField(default="client#1", max_length=100),
        ),
        migrations.AlterField(
            model_name="sut",
            name="name",
            field=models.CharField(default="sut", max_length=100),
        ),
    ]
