# Generated by Django 5.1 on 2024-08-12 02:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sutclient", "0005_remove_config_auto_increment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="switchconfig",
            name="bond_modes",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(), default=[1, 2, 4], size=None
            ),
        ),
        migrations.AlterField(
            model_name="switchconfig",
            name="portchannel_no",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(), default=[1, 2, 3], size=None
            ),
        ),
        migrations.AlterField(
            model_name="switches",
            name="bond_modes",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(), default=[1, 2, 4], size=None
            ),
        ),
        migrations.AlterField(
            model_name="switches",
            name="portchannel_no",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(), default=[1, 2, 3], size=None
            ),
        ),
    ]
