# Generated by Django 5.1 on 2024-08-12 02:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sutclient", "0006_alter_switchconfig_bond_modes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fwupgradetype",
            name="upgrade_type",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100),
                default=["repave", "upgrade"],
                size=None,
            ),
        ),
    ]
