# Generated by Django 5.1 on 2024-08-12 03:43

import django.contrib.postgres.fields
import sutclient.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sutclient", "0007_alter_fwupgradetype_upgrade_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="config",
            name="errors_to_flag",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100),
                default=sutclient.models.default_config_errors,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="fwupgradetype",
            name="upgrade_type",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100),
                default=sutclient.models.default_fw_upgrade_types,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="npar",
            name="npar_functions",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(),
                default=sutclient.models.default_npar_functions,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="splpkgfilepath",
            name="spl_pkg_file_path",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100),
                default=sutclient.models.default_spl_pkg_file_path,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="switchconfig",
            name="bond_modes",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(),
                default=sutclient.models.default_bond_modes,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="switchconfig",
            name="portchannel_no",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(),
                default=sutclient.models.default_portchannel_no,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="switches",
            name="bond_modes",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(),
                default=sutclient.models.default_bond_modes,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="switches",
            name="portchannel_no",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(),
                default=sutclient.models.default_portchannel_no,
                size=None,
            ),
        ),
    ]
