# Generated by Django 5.1 on 2024-08-12 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sutclient", "0008_alter_config_errors_to_flag_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rmii",
            name="instance_id",
            field=models.IntegerField(default=1),
        ),
    ]
